version: '3.8'

services:
  # Hyperion Coordinator MCP Server
  hyperion-coordinator-mcp:
    build:
      context: ./coordinator/mcp-server
      dockerfile: Dockerfile
    container_name: hyperion-coordinator-mcp
    environment:
      # MongoDB Configuration
      - MONGODB_URI=${MONGODB_URI:-mongodb+srv://dev:fvOKzv9enD8CSVwD@devdb.yqf8f8r.mongodb.net/?retryWrites=true&w=majority&appName=devDB}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-coordinator_db}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    stdin_open: true    # Required for stdio MCP transport
    tty: true           # Required for stdio MCP transport
    networks:
      - hyperion-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "hyperion-coordinator-mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  hyperion-network:
    driver: bridge
    name: hyperion-network
